language: python

python:
  - "2.7"

env:
  - TOXENV=py27-trunk
  - TOXENV=py27-1.7.X
  - TOXENV=py27-1.6.X,py26-1.6.X
  - TOXENV=py27-1.5.X,py26-1.5.X
  - TOXENV=py27-1.4.X,py26-1.4.X
  - TOXENV=flake8
  - TOXENV=coverage
  - TOXENV=docs

install:
  - pip install tox

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py27-trunk
